// Generated by Selenium IDE
package com.online.hotel.arlear;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PruebaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("https://online-hotel-frontend.herokuapp.com/reservations");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".formItem:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(5)")).sendKeys("2020-05-06");
    driver.findElement(By.cssSelector(".formItem:nth-child(9)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(9)")).click();
    driver.findElement(By.cssSelector(".formItem:nth-child(9)")).sendKeys("2020-05-21");
    driver.findElement(By.cssSelector("body")).click();
  }
}
