package com.online.hotel.arlear;

/*public class ReservationTest {

}*/
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ReservationTest {
//public class CDP1ReservaTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
//@SuppressWarnings("deprecation")
@Test
//public void cDP1Reserva() 
public void cDP18ReservaContactosimbolosnombres() {
    driver.get("http://localhost:8090/recepcion");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.linkText("Seleccione tipo de reserva...")).click();
    driver.findElement(By.cssSelector(".active-result:nth-child(4)")).click();
    driver.findElement(By.id("checkin")).click();
    driver.findElement(By.id("checkin")).sendKeys("06-08-2020");
    driver.findElement(By.id("checkout")).click();
    driver.findElement(By.id("checkout")).sendKeys("08-08-2020");
    /*driver.findElement(By.id("dia34")).click();
    driver.findElement(By.id("checkout")).click();
    driver.findElement(By.id("dia36")).click();*/
    driver.findElement(By.id("adultsCuantity")).click();
    driver.findElement(By.id("adultsCuantity")).sendKeys("4");
    driver.findElement(By.id("childsCuantity")).click();
    driver.findElement(By.id("childsCuantity")).sendKeys("1");
    //driver.findElement(By.id("serviceType")).click();
    /*{
      WebElement dropdown = driver.findElement(By.id("serviceType"));
      dropdown.findElement(By.xpath("//option[. = 'Desayuno incluido']")).click();
    }
    driver.findElement(By.id("serviceType")).click();*/
   // driver.findElement(By.id("roomType")).click();
    {
      WebElement dropdown = driver.findElement(By.id("roomType"));
      dropdown.findElement(By.xpath("//option[. = 'Simple']")).click();
    }
    driver.findElement(By.id("roomType")).click();
    driver.findElement(By.id("submitReservation")).click();
    driver.findElement(By.cssSelector("#roomSelect_chosen span")).click();
    driver.findElement(By.cssSelector("#roomSelect_chosen .active-result:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".submitInput:nth-child(9)")).click();
    driver.findElement(By.id("idtype")).click();
    driver.findElement(By.id("idtype")).click();
    driver.findElement(By.id("idnumber")).click();
    driver.findElement(By.id("idnumber")).sendKeys("123456789");
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("G124\"#$%");
    driver.findElement(By.cssSelector(".slide:nth-child(3)")).click();
    driver.findElement(By.id("surname")).click();
    driver.findElement(By.id("surname")).sendKeys("A122#$$%");
    driver.findElement(By.id("gender")).click();
    {
      WebElement dropdown = driver.findElement(By.id("gender"));
      dropdown.findElement(By.xpath("//option[. = 'Femenino']")).click();
    }
    driver.findElement(By.id("gender")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("GG@mail.com");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("1234567890");
    driver.findElement(By.id("cardtype")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cardtype"));
      dropdown.findElement(By.xpath("//option[. = 'Tarjeta de debito']")).click();
    }
    driver.findElement(By.id("cardtype")).click();
    driver.findElement(By.linkText("Seleccione medio de pago...")).click();
    driver.findElement(By.cssSelector("#paymentMethod_chosen .active-result:nth-child(3)")).click();
    driver.findElement(By.id("titularname")).click();
    driver.findElement(By.id("titularname")).sendKeys("G288..&&");
    driver.findElement(By.id("cardnumber")).click();
    driver.findElement(By.id("cardnumber")).sendKeys("1234567890123456");
    driver.findElement(By.id("expiration")).click();
    driver.findElement(By.id("expiration")).sendKeys("02/30");
    driver.findElement(By.id("securitycode")).click();
    driver.findElement(By.id("securitycode")).sendKeys("1234");
    driver.findElement(By.cssSelector(".submitInput:nth-child(30)")).click();
    assertThat(driver.findElement(By.cssSelector(".itemError:nth-child(3)")).getText(), is("-Seleccione un tipo de dni"));
    assertThat(driver.findElement(By.cssSelector(".itemError:nth-child(4)")).getText(), is("-Ingrese nombre del contacto"));
    assertThat(driver.findElement(By.cssSelector(".itemError:nth-child(5)")).getText(), is("-Ingrese apellido del contacto"));
    assertThat(driver.findElement(By.cssSelector(".itemError:nth-child(6)")).getText(), is("-Ingrese nombre completo del titular"));
  }
}
